# Generated by Django 5.2.10 on 2026-01-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome projeto')),
                ('objetivo', models.TextField(default='Insira objetivo', max_length=250, verbose_name='Descrição curta em 250 caracteres')),
                ('datainicio', models.DateField(default='AAAA-MM-DD', verbose_name='Data inicial')),
                ('datafinal', models.DateField(blank=True, null=True, verbose_name='Data final')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Data final prevista(opcional)')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Em andamento'), ('C', 'Concluído')], max_length=1, verbose_name='Status')),
                ('tipo', models.CharField(choices=[('T', 'Tarefas'), ('E', 'Entregas'), ('A', 'Etapas'), ('M', 'Melhorar'), ('R', 'Revisadas'), ('O', 'Outro')], default='O', max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Subitem do projeto',
                'verbose_name_plural': 'Subitens dos projetos',
            },
        ),
    ]
