# Generated by Django 5.2.10 on 2026-01-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('Telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='número de telefone')),
                ('Email', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('DataNascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
            ],
        ),
    ]
