# Generated by Django 5.2.10 on 2026-01-18 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('System', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='colaboradores',
            field=models.ManyToManyField(default='Sem colaboradores', related_name='collaborating_projects', to=settings.AUTH_USER_MODEL, verbose_name='Colaboradores'),
        ),
        migrations.AddField(
            model_name='project',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Dono do Projeto'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitens', to='System.project', verbose_name='Projeto'),
        ),
    ]
