# Generated by Django 5.2.10 on 2026-01-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
