# Generated by Django 5.2.10 on 2026-01-18 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='resp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo subitem'),
            preserve_default=False,
        ),
    ]
